import { Button } from "@/components/ui/button";
import { FileText, Download } from "lucide-react";
import { toast } from "sonner";

const documents = [
  { name: "Warranty Agreement Template", desc: "Standard warranty agreement for customers", type: "PDF" },
  { name: "Warranty Certificate", desc: "Branded warranty certificate template", type: "PDF" },
  { name: "Marketing Flyer", desc: "Customer-facing warranty flyer", type: "PDF" },
  { name: "Terms & Conditions", desc: "Full terms and conditions document", type: "PDF" },
  { name: "Claims Process Guide", desc: "Step-by-step claims process for customers", type: "PDF" },
];

function generateDocHTML(docName: string): string {
  return `<!DOCTYPE html><html><head><style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Space+Grotesk:wght@500;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; padding: 48px; max-width: 800px; margin: 0 auto; color: #1a1a2e; }
    h1 { font-family: 'Space Grotesk', sans-serif; font-size: 24px; color: #00323D; margin-bottom: 24px; border-bottom: 2px solid #14b8a6; padding-bottom: 12px; }
    h2 { font-family: 'Space Grotesk', sans-serif; font-size: 18px; color: #00323D; margin: 24px 0 12px; }
    p, li { font-size: 14px; line-height: 1.7; color: #444; margin-bottom: 8px; }
    ul { padding-left: 20px; }
    .header { text-align: center; margin-bottom: 32px; }
    .header p { color: #14b8a6; font-weight: 600; font-size: 12px; letter-spacing: 2px; text-transform: uppercase; }
    .footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 11px; color: #999; }
    @media print { body { padding: 24px; } }
  </style></head><body>
    <div class="header"><p>WarrantyVault</p><h1>${docName}</h1></div>
    <h2>1. Overview</h2>
    <p>This document outlines the terms and conditions governing the self-funded warranty program managed through the WarrantyVault platform.</p>
    <h2>2. Coverage</h2>
    <p>The warranty covers mechanical and electrical failures of the following components:</p>
    <ul>
      <li>Engine and internal components</li>
      <li>Gearbox and transmission</li>
      <li>Differential and drive shafts</li>
      <li>Electrical systems (excluding consumables)</li>
      <li>Cooling and fuel systems</li>
      <li>Steering and suspension</li>
    </ul>
    <h2>3. Exclusions</h2>
    <p>This warranty does not cover:</p>
    <ul>
      <li>Normal wear and tear items (brakes, clutch, tyres, wipers)</li>
      <li>Cosmetic damage or bodywork</li>
      <li>Pre-existing faults</li>
      <li>Modifications or aftermarket parts</li>
      <li>Damage caused by neglect or misuse</li>
    </ul>
    <h2>4. Claims Process</h2>
    <p>To submit a claim, log into your customer portal at WarrantyVault and complete the claims form. You will need to provide a description of the fault, photographs, and a garage diagnosis where applicable.</p>
    <h2>5. Contact</h2>
    <p>For any queries, please contact your dealership directly or reach out via the WarrantyVault platform.</p>
    <div class="footer">
      <p>Generated by WarrantyVault • Self-Funded Warranty Management Platform</p>
      <p>© ${new Date().getFullYear()} WarrantyVault — Built by Wildcard Labs</p>
    </div>
  </body></html>`;
}

function handleDownload(doc: { name: string }) {
  const html = generateDocHTML(doc.name);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${doc.name.replace(/\s+/g, "-").toLowerCase()}.html`;
  a.click();
  URL.revokeObjectURL(url);
  toast.success(`${doc.name} downloaded`);
}

function handleView(doc: { name: string }) {
  const html = generateDocHTML(doc.name);
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

export default function DealerDocuments() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold font-display">Documents</h1>
        <p className="text-sm text-muted-foreground">Download and view pre-made documents for your dealership</p>
      </div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {documents.map(doc => (
          <div key={doc.name} className="glass-card rounded-xl p-5 hover:border-primary/30 transition-all group">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <h3 className="font-medium mb-1">{doc.name}</h3>
            <p className="text-sm text-muted-foreground mb-4">{doc.desc}</p>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => handleDownload(doc)}>
                <Download className="w-4 h-4 mr-2" /> Download
              </Button>
              <Button variant="ghost" size="sm" onClick={() => handleView(doc)}>
                View
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
